* Google Hash Code - 2016

** Algoritmo de rellenado

1. Sobre una matriz se recorre de uno en uno desde arriba a la
   izquierda las casillas hasta encontar una coloreada.
2. Comenzamos pensando en el cuadrado 3x3.
   1. Si se sale de los límites, vamos al PUNTO 3.
   2. Miramos el siguiente en tamaño (3x3, 5x5, 7x7,...,[2N-1]x[2N-1])
      1. Comprobamos si el porcentaje de pintado es mejor que el
         anterior cuadrado.
      2. Si es mejor, vamos al PUNTO 2.2
      3. Si es peor, reservamos el anterior cuadrado.
3. Avanzamos a la siguiente casilla original coloreada.
   1. Si hemos acabado, vamos al punto 4
   2. Si no, vamos al PUNTO 2.

4. Sobre una matriz se recorre de uno en uno desde arriba a la
   izquierda las casillas hasta encontar una coloreada.
5. Comenzamos pensando en una línea horizontal.
   1. Miramos hasta qué porcentaje alargándola es el óptimo de coloración.
6. Avanzamos a la siguiente casilla coloreada original.

PENDIENTE...

** Algoritmo de rellenado 2

*** 1. Se crea una matriz de copia identica a la original en dimensiones, pero con todos sus campos a false.
*** 2. Se va recorriendo la matriz por filas, de izquierda a derecha y de arriba abajo.
*** 3. Una vez se encuentra una casilla coloreada en la matriz original, se inicia la busqueda de casillas coloreadas adyacentes.
**** 1. Primero buscamos un recuadro 3*3. En caso de encontrar 7 o más casillas true, lo coloreamos.
**** 2. Si no hay 7 o más casillas en el recuadro, recorremos la fila de la casilla referencia.
**** 3. En caso de no encontrar casillas adyacentes en la fila, las buscaremos en la columna.
*** 4. Avanzamos a la siguiente casilla en la matriz original que esté a true y no haya sido copiada. Se repite el paso 3.
*** 5. Una vez hemos copiado todas las casillas true, tenemos que devolver a false todas aquellas que se hayan copiado dentro de la creación de cuadrados.

